---
- name: Nessus Setup
  hosts: local
  become: yes

  tasks:
  - name: Download Tenable
    get_url:
      url: https://www.tenable.com/downloads/api/v1/public/pages/nessus/downloads/11053/download?i_agree_to_tenable_license_agreement=true
      dest: /tmp/nessus_installer.deb

  - name: Install Tenable
    apt:
      deb: /tmp/nessus_installer.deb

  - name: Start Tenable and Enable Auto-Start
    systemd:
      state: started
      enabled: yes
      name: nessusd


- name: Splunk Universal Forwarder Setup
  hosts: local
  become: yes
  
  tasks:
  - name: Download the Universal Forwarder
    get_url:
      url: https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.0.4&product=universalforwarder&filename=splunkforwarder-8.0.4-767223ac207f-linux-2.6-amd64.deb&wget=true
      dest: /tmp/splunk_installer.deb

  - name: Install the Universal Forwarder
    apt:
      deb: /tmp/splunk_installer.deb

  - name: Start the Universal Forwarder
    command: chdir=/opt/splunkforwarder/bin ./splunk start --accept-license


- name: Suricata Setup
  hosts: local
  become: yes
  
  tasks:

  - name: Set Up Suricata Repository
    apt_repository:
        repo: ppa:oisf/suricata-stable

  - name: Install Suricata
    apt:
      update_cache: yes
      name: suricata
      state: present
  
  - name: Start Suricata and Enable Auto-Start
    systemd:
      state: started
      enabled: yes
      name: suricata
