---
- name: Nessus Setup
  hosts: local
  become: yes

  tasks:
  - name: Download Tenable
    get_url:
      url: https://www.tenable.com/downloads/api/v1/public/pages/nessus/downloads/11053/download?i_agree_to_tenable_license_agreement=true
      dest: /tmp/nessus_installer.deb

  tasks:
  - name: Install Tenable
    apt:
      deb: /tmp/nessus_installer.deb
  
  tasks:
  - name: Start Tenable and Enable Auto-Start
    systemd:
      state: started
      enabled: yes
      name: nessusd


- name: Splunk Universal Forwarder Setup
  hosts: local
  become: yes
  
  tasks:
  - name: Download the Universal Forwarder
    git:
      repo: https://github.com/tbcsec/Splunkforwarder.git
      dest: /tmp/splunk_installer

  - name: Install the Universal Forwarder
    apt:
      deb: /tmp/splunk_installer/splunkforwarder-8.0.3-a6754d8441bf-linux-2.6-amd64.deb

  - name: Start the Universal Forwarder
    command: chdir=/opt/splunkforwarder/bin ./splunk start --accept-license


- name: Suricata Setup
  hosts: local
  become: yes
  
  tasks:

  - name: Set up suricata repository
    apt_repository:
        repo: ppa:oisf/suricata-stable

  - name: install suricata
    apt:
      update_cache: yes
      name: suricata
      state: present
  
  - name: start suricata
    command: systemctl start suricata
