---
- name: Initial Setup
  hosts: local
  become: yes
  
  tasks:
  - name: Update and Install Dependancies
    apt:
      update_cache: yes
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl

- name: Nessus Setup
  hosts: local
  become: yes

  tasks:
  - name: Bring Up Nessus
    docker_container:
      name: nessus
      image: tbconsulting/nessus:1.0
      ports:
        - 8834:8834


- name: UF Setup
  hosts: local
  become: yes
  
  tasks:

  - name: wget UF tar file from Splunk
    command: wget -O splunkforwarder-8.0.3-a6754d8441bf-Linux-x86_64.tgz 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.0.3&product=universalforwarder&filename=splunkforwarder-8.0.3-a6754d8441bf-Linux-x86_64.tgz&wget=true'

  - name: Untar file
    command: chdir=/home/dakota/SecurityPostureAssessment tar -xvzf splunkforwarder-8.0.3-a6754d8441bf-Linux-x86_64.tgz
  
  - name: start splunk
    command: chdir=/home/dakota/SecurityPostureAssessment/splunkforwarder/bin ./splunk start --accept-license
 
- name: Suricata Setup
  hosts: local
  become: yes
  
  tasks:

  - name: Update and Install Dependancies
    apt:
      update_cache: yes
      pkg:
      - libpcre3-dbg
      - libpcre3-dev
      - autoconf 
      - automake 
      - libtool 
      - libpcap-dev 
      - libnet1-dev 
      - libyaml-dev 
      - libjansson4 
      - libcap-ng-dev 
      - libmagic-dev 
      - libjansson-dev 
      - zlib1g-dev 
      - pkg-config 
      - rustc 
      - cargo
      - python-apt

  - name: wget Suricata tar file
    command: chdir=/home/dakota/SecurityPostureAssessment wget https://www.openinfosecfoundation.org/download/suricata-5.0.0.tar.gz

  - name: Untar file
    command: chdir=/home/dakota/SecurityPostureAssessment tar -xvzf suricata-5.0.0.tar.gz 
  
  - name: copy files over to /etc/suricata
    command: chdir=/home/dakota/SecurityPostureAssessment/suricata-5.0.0/etc cp reference.config /etc/suricata

  - name: copy files over over to /etc/suricata
    command: chdir=/home/dakota/SecurityPostureAssessment/suricata-5.0.0/etc cp classification.config /etc/suricata

  - name: copy files over over to /etc/suricata
    command: chdir=/home/dakota/SecurityPostureAssessment/suricata-5.0.0 cp suricata.yaml.in /etc/suricata

  - name: Set up suricata repository
    apt_repository:
        repo: ppa:oisf/suricata-stable

  - name: install suricata
    apt:
      update_cache: yes
      name: suricata
      state: present
  
  - name: start suricata
    command: chdir=/home/dakota/SecurityPostureAssessment systemctl start suricata
